# Phase 2 — Pseudo-labels from reports

Hybrid report labeling (rules + optional LLM) → train ConvNeXt-Tiny MIL on 4,407 studies.

- OOF metric computed on **58 labeled** studies only (compare to Phase 1 baseline 0.5295).
- Test inference is **image-only** (no reports).
- Pretrained backbone: set `cfg["model"]["pretrained_weights"]` / `variant` in export script.
- Daily: Cursor → Kaggle Jupyter Server ([docs/KAGGLE.md](../docs/KAGGLE.md)).
- Submit: `python scripts/push_kaggle_kernel.py phase2` → Save & Run All.

## Setup

In [19]:
from __future__ import annotations

import importlib
import json
import shutil
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch


def _src() -> Path:
    work = Path("/kaggle/working")
    work_src = work / "src"
    mount = Path("/kaggle/input/rsna-knee-code")
    mount_src = mount / "src"
    reports = work_src / "rsna_knee" / "reports"
    if work.is_dir() and (mount_src / "rsna_knee").is_dir():
        need_copy = not (work_src / "rsna_knee").is_dir()
        need_overlay = (work_src / "rsna_knee").is_dir() and not reports.is_dir()
        if need_copy:
            shutil.copytree(mount_src, work_src)
        elif need_overlay:
            shutil.copytree(mount_src, work_src, dirs_exist_ok=True)
        if (need_copy or need_overlay) and (mount / "configs").is_dir():
            shutil.copytree(mount / "configs", work / "configs", dirs_exist_ok=True)
    if (work_src / "rsna_knee").is_dir():
        if not reports.is_dir():
            raise FileNotFoundError(
                "rsna_knee.reports missing under /kaggle/working/src. "
                "Run: python scripts/sync_code_to_jupyter.py"
            )
        return work_src
    for root in (Path.cwd(), Path.cwd().parent):
        src = root / "src"
        if (src / "rsna_knee").is_dir():
            return src
    raise FileNotFoundError("Run: python scripts/sync_code_to_jupyter.py")


def _refresh_rsna_knee(src: Path) -> None:
    """Drop bytecode + in-memory modules so a re-run picks up a just-synced src/."""
    for cache in src.rglob("__pycache__"):
        shutil.rmtree(cache, ignore_errors=True)
    importlib.invalidate_caches()
    for key in list(sys.modules):
        if key == "rsna_knee" or key.startswith("rsna_knee."):
            del sys.modules[key]


_SRC = _src()
_src_str = str(_SRC)
sys.path = [_src_str] + [p for p in sys.path if p != _src_str]
_refresh_rsna_knee(_SRC)
REPO_ROOT = _SRC.parent

from rsna_knee.constants import TARGET_LABELS
from rsna_knee.data import load_test_table, predictions_to_submission
from rsna_knee.data.schema import labels_present_mask, load_train_table
from rsna_knee.models.weights import resolve_pretrained_weights
from rsna_knee.reports import evaluate_labeler, generate_pseudo_labels, report_eda_summary
from rsna_knee.reports.rules import RuleLabeler
from rsna_knee.training import macro_roc_auc, predict_test_ensemble, run_phase2_training
from rsna_knee.utils.config import load_config
from rsna_knee.utils.paths import default_data_root, is_kaggle_kernel

ON_KAGGLE = is_kaggle_kernel()
CFG_NAME = "kaggle_phase2" if ON_KAGGLE else "phase2"
cfg = load_config(CFG_NAME)
DATA_ROOT = default_data_root()
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
OUT_DIR = Path(cfg["paths"]["output_dir"])
if not OUT_DIR.is_absolute():
    OUT_DIR = REPO_ROOT / OUT_DIR
OUT_DIR.mkdir(parents=True, exist_ok=True)

print(f"Environment : {'Kaggle' if ON_KAGGLE else 'local'}")
print(f"Data root   : {DATA_ROOT}")
print(f"Package     : {_SRC}")
print(f"Config      : {CFG_NAME}")

Environment : Kaggle
Data root   : /kaggle/input/competitions/rsna-knee-abnormality-detection
Package     : /kaggle/working/src
Config      : kaggle_phase2

## 1. Report EDA

In [2]:
eda = report_eda_summary(DATA_ROOT)
print(json.dumps(eda, indent=2))
display(pd.DataFrame(eda["language_distribution"]))
display(pd.DataFrame(eda["keyword_hit_rates_labeled"]))

{
  "n_studies": 4407,
  "n_labeled": 58,
  "length_stats": {
    "n_reports": 4407.0,
    "chars_mean": 1097.905604719764,
    "chars_median": 977.0,
    "chars_p95": 2452.7,
    "words_mean": 147.54299977308827,
    "words_median": 129.0
  },
  "language_distribution": [
    {
      "language": "english",
      "count": 1750,
      "fraction": 0.3970955298388927
    },
    {
      "language": "other",
      "count": 1506,
      "fraction": 0.3417290673927842
    },
    {
      "language": "spanish",
      "count": 742,
      "fraction": 0.16836850465169048
    },
    {
      "language": "german",
      "count": 409,
      "fraction": 0.09280689811663263
    }
  ],
  "keyword_hit_rates_labeled": [
    {
      "label": "joint_effusion",
      "hit_rate": 0.5172413793103449,
      "accuracy": 0.5862068965517241,
      "n": 58
    },
    {
      "label": "acl_tear",
      "hit_rate": 0.4482758620689655,
      "accuracy": 0.603448275862069,
      "n": 58
    },
    {
      "label": "mcl_tear",
      "hit_rate": 0.4482758620689655,
      "accuracy": 0.7241379310344828,
      "n": 58
    },
    {
      "label": "medial_meniscus_injury",
      "hit_rate": 0.41379310344827586,
      "accuracy": 0.5862068965517241,
      "n": 58
    },
    {
      "label": "lateral_meniscus_injury",
      "hit_rate": 0.39655172413793105,
      "accuracy": 0.6896551724137931,
      "n": 58
    },
    {
      "label": "bone_contusion",
      "hit_rate": 0.3103448275862069,
      "accuracy": 0.6896551724137931,
      "n": 58
    },
    {
      "label": "fracture",
      "hit_rate": 0.1896551724137931,
      "accuracy": 0.8103448275862069,
      "n": 58
    },
    {
      "label": "patellofemoral_osteoarthritis",
      "hit_rate": 0.1724137931034483,
      "accuracy": 0.5344827586206896,
      "n": 58
    },
    {
      "label": "bakers_cyst",
      "hit_rate": 0.15517241379310345,
      "accuracy": 0.8448275862068966,
      "n": 58
    },
    {
      "label": "synovitis",
      "hit_rate": 0.15517241379310345,
      "accuracy": 0.5862068965517241,
      "n": 58
    },
    {
      "label": "medial_osteoarthritis",
      "hit_rate": 0.017241379310344827,
      "accuracy": 0.7586206896551724,
      "n": 58
    },
    {
      "label": "lateral_osteoarthritis",
      "hit_rate": 0.0,
      "accuracy": 0.8103448275862069,
      "n": 58
    }
  ]
}

  language  count  fraction
0  english   1750  0.397096
1    other   1506  0.341729
2  spanish    742  0.168369
3   german    409  0.092807

                            label  hit_rate  accuracy   n
0                  joint_effusion  0.517241  0.586207  58
1                        acl_tear  0.448276  0.603448  58
2                        mcl_tear  0.448276  0.724138  58
3          medial_meniscus_injury  0.413793  0.586207  58
4         lateral_meniscus_injury  0.396552  0.689655  58
5                  bone_contusion  0.310345  0.689655  58
6                        fracture  0.189655  0.810345  58
7   patellofemoral_osteoarthritis  0.172414  0.534483  58
8                     bakers_cyst  0.155172  0.844828  58
9                       synovitis  0.155172  0.586207  58
10          medial_osteoarthritis  0.017241  0.758621  58
11         lateral_osteoarthritis  0.000000  0.810345  58

## 2. Validate rule labeler on 58 labeled studies

In [4]:
rule_metrics, rule_macro_f1 = evaluate_labeler(RuleLabeler(), DATA_ROOT)
print(f"Rule labeler macro F1: {rule_macro_f1:.3f}")
display(rule_metrics.sort_values("f1", ascending=False))

Rule labeler macro F1: 0.394

,label,precision,recall,f1,auc,support_pos,support_neg
3,lateral_meniscus_injury,0.619048,0.565217,0.590909,0.668323,23,35
7,joint_effusion,0.761905,0.457143,0.571429,0.619876,35,23
11,fracture,1.000000,0.388889,0.560000,0.694444,18,40
0,acl_tear,0.518519,0.583333,0.549020,0.600490,24,34
10,bone_contusion,0.529412,0.473684,0.500000,0.634278,19,39
1,mcl_tear,0.333333,0.777778,0.466667,0.746032,9,49
2,medial_meniscus_injury,0.555556,0.384615,0.454545,0.567308,26,32
9,bakers_cyst,1.000000,0.250000,0.400000,0.625000,12,46
8,synovitis,0.666667,0.222222,0.333333,0.562724,27,31
6,patellofemoral_osteoarthritis,0.250000,0.142857,0.181818,0.449807,21,37
4,medial_osteoarthritis,1.000000,0.066667,0.125000,0.533333,15,43
5,lateral_osteoarthritis,0.000000,0.000000,0.000000,0.500000,11,47

## 2b. LLM confirmer on 58 labeled studies

Rules stay as the proposal. A small instruct model (**Qwen2.5-1.5B-Instruct**, Apache-2.0) must **agree** before ACL/MCL/OA/synovitis rule-positives are kept. Vetoes are masked (`confidence=0`), not trained as negatives.

High-precision rules (fracture, Baker, effusion, menisci) are not sent to the LLM.

**Kaggle:** the model is already attached at `/kaggle/input/models/qwen-lm/qwen2.5/transformers/1.5b-instruct/1`. Sync `src/`, re-run Setup, then this cell. `LLM source` should print that path — not a HuggingFace hub id.

In [11]:
from rsna_knee.reports import HybridLabeler, LLMLabeler, RuleLabeler
from rsna_knee.reports.llm import DEFAULT_CONFIRM_LABELS, DEFAULT_LLM_MODEL_ID

rpt = cfg.get("reports", {})
confirm_labels = list(rpt.get("confirm_labels") or DEFAULT_CONFIRM_LABELS)
llm = LLMLabeler(
    model_path=rpt.get("llm_model_path"),
    model_id=rpt.get("llm_model_id") or DEFAULT_LLM_MODEL_ID,
    device="auto",
    verbose=True,
)
print(f"LLM source : {llm.describe()}")
print(f"Confirm    : {confirm_labels}")
if llm.source_kind == "hub":
    raise RuntimeError(
        "Resolved a HuggingFace hub id; the kernel would download from huggingface.co. "
        "Attach Qwen/Qwen2.5-1.5B-Instruct via Add Input → Models, restart Jupyter, "
        "sync src/, then re-run Setup."
    )
llm.warmup()
print("LLM ready")

hybrid = HybridLabeler(
    llm_labeler=llm,
    confirm_labels=confirm_labels,
    fill_ambiguous=bool(rpt.get("fill_ambiguous", False)),
    route_threshold=float(rpt.get("route_threshold", 0.7)),
    verbose=True,
)
hybrid_metrics, hybrid_macro_f1 = evaluate_labeler(hybrid, DATA_ROOT)

# Rules eval is cheap; recompute if this cell was run without section 2.
if "rule_metrics" not in globals() or "rule_macro_f1" not in globals():
    rule_metrics, rule_macro_f1 = evaluate_labeler(RuleLabeler(), DATA_ROOT)

print(f"Hybrid macro F1: {hybrid_macro_f1:.3f}  (rules {rule_macro_f1:.3f})")

cmp = rule_metrics[["label", "precision", "recall", "f1"]].merge(
    hybrid_metrics[["label", "precision", "recall", "f1"]],
    on="label",
    suffixes=("_rule", "_hybrid"),
)
cmp["precision_delta"] = cmp["precision_hybrid"] - cmp["precision_rule"]
display(cmp.sort_values("precision_hybrid", ascending=False))
display(hybrid_metrics.sort_values("f1", ascending=False))

LLM source : kaggle:/kaggle/input/models/qwen-lm/qwen2.5/transformers/1.5b-instruct/1
Confirm    : ['acl_tear', 'mcl_tear', 'medial_osteoarthritis', 'lateral_osteoarthritis', 'patellofemoral_osteoarthritis', 'synovitis']

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

LLM ready

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 1 ===
Asked keys : ['lateral_osteoarthritis']
Report (1199 chars):
Antecedentes Clínicos:
Esguince rodilla. [DATE].
Hallazgos:
No hay alteraciones de señal significativas de la médula ósea.
Ligamentos cruzados y colaterales dentro de límites normales.
Amputación marginal del cuerpo del menisco lateral. Menisco medial de morfología y señal
conservada, sin signos de rotura.
Cartílagos de los compartimentos femorotibiales sin alteraciones.
Fina úlcera condral focal de espesor total del aspecto inferior de la vertiente medial de la tróclea
femoral con mínimos cambios óseos secundarios. Fenómenos condrales reparativos de la región
central de la simple femoral. Cartílago rotuliano sin alteraciones.
Leve derrame articular. No hay quistes poplíteos patológicos.
Aumento de señal de la inserción distal del tendón cuadricipital y de la inserción proximal del
tendón rotuliano, sin signos de rotura.
No hay alteraciones de señal de la grasa de Hoffa.
Impresión:
Amputación marginal del cuerpo del menisco lateral.
Condropatía focal grado 4 del aspecto inferior de la vertiente medial de la tróclea femoral .
Fenómenos condrales reparativos de la región central de la tróclea femoral.
Leve derrame articular.
Leve tendinosis cuadricipital distal y rotuliana proximal.
Raw reply:
```json
{
  "lateral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'lateral_osteoarthritis': 1}
=== Match 1 (rule AND llm → keep; veto → mask conf=0) ===
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 2 ===
Asked keys : ['synovitis']
Report (1190 chars):
 The study reveals normal knee joint alignment.   No fracture is seen.
   ACL is intact.   PCL is preserved.
  The MCL is intact.    Medial meniscus is not torn.
  The FCL, popliteus and biceps femoris tendons are preserved.
   Horizontal tear at anterior horn of the lateral meniscus is noted.
   Focal osteochondral defect at lateral patellar facet, about 8x12mm. with subchondral bone edema is detected.   Full thickness cartilage defect, 1.2x1.5cm. at lateral trochlea with subchondral bone edema is noted.   Small osteochondral body, about intact9xintact4cm. at anterior infrapatellar recess is noted.
  The quadriceps and patellar tendons are preserved.
   Moderate joint effusion, distended suprapatellar bursa with thickend synovial tissue are observed.  Horizontal tear at anterior horn of the lateral meniscus.
     Osteochondral fracture at lateral patellar facet, about 8x12mm. with dislodge OCD fragment.
     Full thickness cartilage defect, 1.2x1.5cm. at lateral trochlea with subchondral bone edema.
      Small osteochondral body, about intact9xintact4cm. at anterior infrapatellar recess.
      Chronic reactive synovitis, suprapatellar bursitis
Raw reply:
```json
{
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'synovitis': 1}
=== Match 2 (rule AND llm → keep; veto → mask conf=0) ===
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 3 ===
Asked keys : ['medial_osteoarthritis', 'lateral_osteoarthritis', 'patellofemoral_osteoarthritis']
Report (2609 chars):
Exam Type: MRI KNEE RIGHT WO CONTRAST
Exam Date and Time: [DATE] [TIME]
Indication: 2 years of pain with walking up and down the stairs twisting and squatting.
Comparison: No relevant prior studies available for comparison.

TECHNIQUE:
MRI of the right knee was performed on a 1.5 Tesla system body coil in three planes (axial, sagittal, and coronal), using a standard non-contrast protocol.

FINDINGS:
OSSEOUS STRUCTURES:
Alignment is anatomic. No acute fracture or bone bruise. Background marrow signal is normal without infiltrative marrow process. No aggressive osseous lesions. Tricompartmental marginal osteophytes

JOINT SPACE:
Small joint effusion. No intra-articular bodies. No Baker's cyst.

MEDIAL COMPARTMENT:
Medial meniscus: Extensive complete tearing of the body, posterior horn, and posterior root medial meniscus with severe extrusion.
Medial compartment cartilage: Full thickness cartilage loss along the medial femoral condyle and medial tibial plateau with subchondral cystic change and marrow edema.

LATERAL COMPARTMENT:
Lateral meniscus: Degenerative signal throughout the lateral meniscus without surfacing tear.
Lateral compartment cartilage: Mild cartilage heterogeneity and fissuring.

PATELLOFEMORAL COMPARTMENT:
Patellofemoral compartment cartilage: High-grade cartilage loss along the medial patellar facet. High grade cartilage loss at lateral trochlea.

CRUCIATE LIGAMENTS:
Anterior cruciate ligament (ACL): Normal with both bundles intact.
Posterior cruciate ligament (PCL): Normal.

COLLATERAL LIGAMENTS & POSTEROLATERAL CORNER:
Medial collateral ligament (MCL): Normal.
Lateral collateral ligament (LCL) complex: Normal.
Posterolateral corner structures: Normal.

EXTENSOR MECHANISM:
Distal quadriceps tendon: No tendinosis or tear.
Patella tendon: No tendinosis o
… [2609 chars total]
Raw reply:
```json
{
  "medial_osteoarthritis": 1,
  "lateral_osteoarthritis": 0,
  "patellofemoral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'medial_osteoarthritis': 1, 'lateral_osteoarthritis': 0, 'patellofemoral_osteoarthritis': 1}
=== Match 3 (rule AND llm → keep; veto → mask conf=0) ===
  medial_osteoarthritis: rule=1 llm=1 → confirm (keep 1)
  lateral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  patellofemoral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 4 ===
Asked keys : ['synovitis']
Report (1290 chars):
MRI of left Knee with
-3-Plane Loc R'T, Sag PD FS, AX T2 FS, Sag T2 FS, Sag T1, CORT2 FS

> There is no abnormal intensity or articular surface disrupt in the medial meniscus, It appears to be normal.
> There is no increased intensity in the ACL, MCL and LCL, it appears to be normal
> Interstitial high intensity, irregular contour and laxity in the PCL, suspected complete tear
> Synovial membrane thickening in the knee joint with fluid accumulation and hofa fat pad stranding, knee arthritis with hoffitis noted
> Fluid accumulated in the suprapatella bursa with quadricep and prefemoral fat pad stranding, suprapatellar bursitis noted
> Fluid accumulated in the posterior medial condyle region
> Medial plica and suprapatellar plicae noted
> Relatively enlarged caliber of the popliteal vein  with heterogenous hyperintensity (srs: 6, Img: 24-30) and prominenet superficial veines, the possiblity of deep vein thrombosis can't totally excluded.

Impression:
1. C/W PCL complete tear, grade 3 injury
2. Synovitis of left knee and massive joint effusion and suprapatellar bursitis; complex plicae.
3. Subcutaneous edema around left knee.
4. R/O deep vein thrombosis of left popliteal vein. Suggest correlation with clinical manifestation
Suggest correlation with clinical manifestation

Raw reply:
```json
{
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'synovitis': 1}
=== Match 4 (rule AND llm → keep; veto → mask conf=0) ===
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 5 ===
Asked keys : ['acl_tear']
Report (988 chars):
 In the medial compartment, there is longitudinal vertical tear at the body and posterior horn of the medial meniscus. There is no focal chondrosis or chondral injury.
 The lateral compartment, the meniscus is not torn and there is no focal chondrosis or chondral injury.
 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact.
 In the intercondylar notch, there is complete tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact. There is anterior tibial translation.
 The medial and lateral collateral ligament complexes are intact. The extensor mechanism is normal.
 No knee effusion is present. The surrounding musculature is normal. There is no fracture or bone contusion.   -- Longitudinal vertical tear at the body and posterior horn of the medial meniscus.
 -- Complete tear of the anterior cruciate ligament, at mid substance.
Raw reply:
```json
{
  "acl_tear": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1}
=== Match 5 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 6 ===
Asked keys : ['acl_tear']
Report (1606 chars):
 In the medial compartment, the meniscus is not torn and there is no focal chondrosis or chondral injury.

 The lateral compartment, there is complex tear (main radial and longitudinal vertical component) at the posterior horn of the lateral meniscus. There is no focal chondrosis or chondral injury.

 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact.
 In the intercondylar notch, there is interstitial tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact. There is no tibial translation.

 The medial collateral ligament complexes are intact. The posteromedial oblique ligament is intact.

 There is grade II ligamentous sprain (partial tear) of  lateral collateral ligament. Partial tear of the intraarticular portion, popliteus tendon is present. The popliteofibular ligament is intact. The meniscopopliteal fascicles are intact.

 The extensor mechanism is normal.

 Some amount of right knee effusion with hemarthrosis is present. There is popliteus muscle contusion.  There is no fracture or bone contusion.   Complex tear (main radial and longitudinal vertical component) at the posterior horn of the lateral meniscus.
  Interstitial tear of the anterior cruciate ligament, at mid substance.
  Grade II ligamentous sprain (partial tear) of  lateral collateral ligament.
  Partial tear of the intraarticular portion, popliteus tendon.
  Some amount of right knee effusion with hemarthrosis.
  Popliteus muscle contusion.
Raw reply:
```json
{
  "acl_tear": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1}
=== Match 6 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 7 ===
Asked keys : ['acl_tear', 'lateral_osteoarthritis']
Report (1493 chars):
Antecedentes Clínicos:
Rodilla traumática aguda.
Hallazgos:
Rotura espesor y ancho total de la unión del tercio medio del tercio proximal del LCA asociado a
discreto edema óseo del aspecto posterior de platillo tibial lateral. LCP y ligamentos colaterales sin
alteraciones significativas.
Aumento de señal central del cuerno posterior y cuerpo del menisco medial que no impresiona
contactar con la superficie articular, sin caracteres propios de rotura.
Menisco lateral con pequeña rotura radial incompleta de la unión del cuerno posterior con el
cuerpo, sin desplazamiento de segmentos.
Úlcera condral de espesor total de la zona de carga del cóndilo femoral lateral que mide
aproximadamente 6 x 5 mm en sus ejes mediolateral y anteroposterior, sin cambios óseos
secundarios. Fina úlcera condral focal de espesor total del aspecto posterior de platillo tibial
lateral. El resto de los cartílagos femorotibiales y patelofemorales sin alteraciones.
Leve a moderado derrame articular, probablemente hemartrosis. Leve cantidad de liquido
intermuscular en la región poplítea.
Tendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial
dentro de límites normales.
Impresión:
Rotura espesor y ancho total del LCA.
Rotura radial incompleta de la unión del cuerno posterior con el cuerpo del menisco lateral.
Condropatía lesiones grado 3 del compartimento femorotibial lateral, previamente descritas.
Leve a moderado derrame articular, probablemente hemartrosis
Raw reply:
```json
{
  "acl_tear": 1,
  "lateral_osteoarthritis": 0
}
```
Parsed JSON for asked keys: {'acl_tear': 1, 'lateral_osteoarthritis': 0}
=== Match 7 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)
  lateral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 8 ===
Asked keys : ['acl_tear', 'mcl_tear', 'synovitis']
Report (1177 chars):
MRI of Knee with
-Locator, SG PD FatSat, SG T2W FS, SG T1W, CO T2W FS, AX T2W FS



* High signal in the soft tissue medial to the medial collateral ligament with mild increased signal intensity of proximal ligament, suspect grade 2 injury.
* Interstitial hyperintense signal of ACL, in favor of grade 1 injury.
* Bone marrow edema in bilateral femoral condyles and anteromedial and posterolateral aspect of proximal tibia, suspect bone contusion.
* Subcutaneous edema over medial aspect of right knee.
* Some joint effusion of right knee with mild hypertrophy of the synovium, indicative of synovitis.
> The contour of ACL & PCL appear to be within normal.
> No evidence of tear noted in either medial or lateral meniscus in this study.
> The quadriceps and patellar tendons appear to be within normal.

Impression:
1. Suspect grade 2 injury of MCL with adjacent soft tissue edema over anteromedial aspect of right knee.
2. Suspect grade 1 injury of ACL.
3. Bone marrow edema in distal femur and proximal tibia (major at anteromedial and posterolateral aspect), suspect bone contusion.
4. Mild synovitis of right knee joint.

Suggest correlation with clinical manifestation.

Raw reply:
```json
{
  "acl_tear": 0,
  "mcl_tear": 1,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 0, 'mcl_tear': 1, 'synovitis': 1}
=== Match 8 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=0 → veto (label=0, conf=0 masked)
  mcl_tear: rule=1 llm=1 → confirm (keep 1)
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 9 ===
Asked keys : ['medial_osteoarthritis', 'lateral_osteoarthritis', 'patellofemoral_osteoarthritis']
Report (2874 chars):
Exam Type: MRI KNEE RIGHT WO CONTRAST
Exam Date and Time: [DATE] [TIME]
Indication: Pain
Comparison: No relevant prior studies available for comparison.

TECHNIQUE:
MRI of the right knee was performed on a 3.0 Tesla system with a dedicated knee coil in three planes (axial, sagittal, and coronal), using a standard non-contrast protocol.

FINDINGS:
OSSEOUS STRUCTURES:
Alignment is anatomic. Subchondral insufficiency fracture at the medial margin of the medial tibial plateau without articular surface collapse. Background marrow signal is normal without infiltrative marrow process. No aggressive osseous lesions.

JOINT SPACE:
Small joint effusion. No intra-articular bodies. Trace Baker's cyst.

MEDIAL COMPARTMENT:
Medial meniscus: Complete radial tear of the posterior root of medial meniscus with mild extrusion.
Medial compartment cartilage: High-grade cartilage fissuring along the posterior weightbearing medial femoral condyle. Mild marginal spurring at the medial joint line.

LATERAL COMPARTMENT:
Lateral meniscus: Partial inner margin radial tear at the anterior horn/body junction of the lateral meniscus without extrusion.
Lateral compartment cartilage: Low-grade cartilage fissuring spanning the weightbearing lateral femoral condyle. High-grade cartilage fissuring along the posterior lateral tibial plateau.

PATELLOFEMORAL COMPARTMENT:
Patellofemoral compartment cartilage: Low-grade cartilage fissuring along the central trochlea. Mild cartilage thinning along the medial patellar facet with mild subchondral cystic change.

CRUCIATE LIGAMENTS:
Anterior cruciate ligament (ACL): Normal with both bundles intact.
Posterior cruciate ligament (PCL): Normal.

COLLATERAL LIGAMENTS & POSTEROLATERAL CORNER:
Medial collateral ligament (MCL): Normal.
Lateral collateral ligament (LCL) c
… [2874 chars total]
Raw reply:
```json
{
  "medial_osteoarthritis": 0,
  "lateral_osteoarthritis": 0,
  "patellofemoral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'medial_osteoarthritis': 0, 'lateral_osteoarthritis': 0, 'patellofemoral_osteoarthritis': 1}
=== Match 9 (rule AND llm → keep; veto → mask conf=0) ===
  medial_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  lateral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  patellofemoral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 10 ===
Asked keys : ['mcl_tear', 'medial_osteoarthritis', 'lateral_osteoarthritis', 'patellofemoral_osteoarthritis', 'synovitis']
Report (2832 chars):
FINDINGS:

Fluid:
Small joint effusion with synovial thickening compatible with synovitis. There is popliteal cyst measuring 21 x 17 x 35 mm. Small amount of edema along the inferior margin of the popliteal cyst suggesting a minimal partial rupture.

Medial compartment (meniscus, collateral ligament, cartilage):
There is increased T2 hyperintense signal within the posterior horn of the medial meniscus extending into the posterior horn-body junction without extension to the articular surface, compatible with intrasubstance degeneration. No frank tear.

Mild thickening of the proximal fibers of the medial cruciate ligament, with mild edema, compatible with grade 1 sprain. No frank tear.

Moderate thinning of the articular cartilage of the weightbearing femur and tibia.

Lateral compartment (meniscus, collateral ligament complex, cartilage):
There is a complex degenerative tear of the lateral meniscus with partial maceration of the anterior horn and anterior body, as well as a longitudinal oblique component involving the posterior horn. There is a 4 mm small displaced fragment along the lateral tibial gutter.

Full-thickness fissures in the articular cartilage of the tibial weightbearing surface with associated subchondral bone marrow edema. There is moderate thinning of the articular cartilage of the weightbearing femur and of the tibial plateau. No subchondral bone marrow edema at the femur.

Mild increased signal intensity at the distal iliotibial band. The lateral collateral ligament complex is otherwise unremarkable.

Intercondylar compartment (anterior and posterior cruciate ligaments):
The anterior and posterior cruciate ligaments are unremarkable. Mild early intraosseous cystic changes at the tibial insertion of the anterior cruciate ligament.

Anterior compartment
… [2832 chars total]
Raw reply:
```json
{
  "mcl_tear": 0,
  "medial_osteoarthritis": 0,
  "lateral_osteoarthritis": 0,
  "patellofemoral_osteoarthritis": 0,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'mcl_tear': 0, 'medial_osteoarthritis': 0, 'lateral_osteoarthritis': 0, 'patellofemoral_osteoarthritis': 0, 'synovitis': 1}
=== Match 10 (rule AND llm → keep; veto → mask conf=0) ===
  mcl_tear: rule=1 llm=0 → veto (label=0, conf=0 masked)
  medial_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  lateral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  patellofemoral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  synovitis: rule=1 llm=1 → confirm (keep 1)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 11 ===
Asked keys : ['acl_tear', 'mcl_tear']
Report (290 chars):
Técnica: RMN de la rodilla. Resultados: Rotura del LCA. Rotura parcial del LCM. Rotura de menisco interno y lateral. Derrame. Contusiones óseas femorotibiales. Impresión: Rotura del LCA. Rotura parcial del LCM. Rotura de menisco interno y lateral. Derrame. Contusiones óseas femorotibiales.
Raw reply:
```json
{
  "acl_tear": 0,
  "mcl_tear": 0
}
```
Parsed JSON for asked keys: {'acl_tear': 0, 'mcl_tear': 0}
=== Match 11 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=0 → veto (label=0, conf=0 masked)
  mcl_tear: rule=1 llm=0 → veto (label=0, conf=0 masked)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 12 ===
Asked keys : ['acl_tear']
Report (1147 chars):
In the medial compartment, the meniscus is not torn and there is no focal chondrosis or chondral injury.
 The lateral compartment, there is longitudinal vertical oblique tear at the posterior horn of the lateral meniscus. There is no focal chondrosis or chondral injury.
 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact.
 In the intercondylar notch, there is complete tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact.
 There is grade II ligamentous sprain (partial tear) of the medial collateral ligament. The posteromedial oblique ligament is intact. The lateral collateral ligament complexes are intact. The extensor mechanism is normal.
 No knee effusion is present. The surrounding musculature is normal. There is no fracture or bone contusion. - Longitudinal vertical oblique tear at the posterior horn of the lateral meniscus.
 - Complete tear of the anterior cruciate ligament, at mid substance.
 - Grade II ligamentous sprain (partial tear) of the medial collateral ligament.
Raw reply:
```json
{
  "acl_tear": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1}
=== Match 12 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 13 ===
Asked keys : ['acl_tear']
Report (990 chars):
> MRI of knee was performed in sagittal, axial and coronal sections.
> Spin echo sequence were used.

> Split fractures at tibial plateau with depression of the lateral articular surface and extending to tibial intercondylar region
> Bone contusion with neglected fracture line at fibular head.
> The contour of ACL is not all in a straight line but increase signal intensity inside, in favor of grade 2 injury.
> The contour of PCL appears to be within normal, no abnormal signal intensity is noted.
> There are linear signal intensity in anterior horn of medial meniscus, it extends into the surface, in favor of tear.
> Medial meniscus appears to be normal.
> Both medial & lateral collateral ligaments appear to be within normal.
> Some joint effusion

Impression:
1. C/W Tibia plateau fracutre and fibular head fracture with bone contusion.
2. Grade 2 injury of anterior cruciate ligament.
3. Tear of anterior horn of lateral meniscus.
Suggest correlation with clinical manifestation

Raw reply:
```json
{
  "acl_tear": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1}
=== Match 13 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 14 ===
Asked keys : ['synovitis']
Report (1264 chars):
[DATE]: MR Knie Rechts 15ch AA: Klinische inlichtingen: Zie gescande aanvraag Diagnostische vraagstelling: Zie gescande aanvraag Bevindingen: Gevorderd lateraal femorotibiaal kraakbeenlijden met volledig kraakbeenverlies anterieur, centrale en posterieure dragende deel en van het laterale tibiaplateau, gepaard gaand met marginale osteofytose, beperkte subchondrale botveranderingen. Degeneratief voorkomen laterale meniscus met opzetting van het corpus, die zich bevindt buiten de gewrichtsspleet . Verder opzetting van suprapatellaire recessus, met talrijke verdikkingen van van het synovium, nodulair beginnend tot matig femoropatellair kraakbeenlijden met meerdere fissuren. Matig mediaal femorotibiaal kraakbeenlijden, met quasi volledig kraakbeenverlies dragende deel mediale femorale condyl, uitgebreide marginale osteofytose,. Gevorderde muco ïde degeneratie van de voorste kruisband, met opgezet voorkomen en gestegen T2-signaal . Popliteale cyste, met beperkte vochtinfiltratie oppervlakkig aan de musculus gastrocnemius medialis . Besluit: Gevorderde gonartrose van de rechterknie, op heden met hydrops, chronische synovitis, gevorderde muco ïde degeneratie voorste kruisband, recente scheur van popliteale cyste , echter zonder significant botoedeem .
Raw reply:
```json
{
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'synovitis': 1}
=== Match 14 (rule AND llm → keep; veto → mask conf=0) ===
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 15 ===
Asked keys : ['lateral_osteoarthritis']
Report (1601 chars):
Antecedentes Clínicos:
Gonalgia izquierda.
Hallazgos:
No hay alteraciones de señal significativas de la médula ósea.
Transformación quística parcial del tercio proximal del LCA. LCP y ligamentos colaterales dentro de límites
normales.
Aumento de señal central del cuerno posterior y cuerpo del menisco medial que contacta la superficie
articular inferior sugieran una rotura.
Rotura del cuerno anterior, cuerpo y cuerno posterior del menisco lateral con mínima extrusión. Esto se
asocia a edema las partes blandas regionales.
Úlceras condrales de espesor parcial y total de la región central de la zona de carga del cóndilo femoral
medial. Úlceras condrales espesor parcial de la región central del platillo tibial lateral. Condropatía
superficial del resto de los cartílagos femorotibiales y de la tróclea femoral.
Úlceras condrales de espesor total de distribución difusa de la rótula.
Leve derrame articular con discreta sinovitis. No hay quistes poplíteos.
Tendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial dentro de
límites normales.
Impresión:
Signos de una rotura del menisco medial, no desplazada.
Rotura compleja del cuerno anterior, cuerpo y cuerno posterior del menisco lateral con mínima extrusión y
edema de las partes blandas regionales.
Condropatía lesiones grado 3 de la región central de la zona de carga del cóndilo femoral medial y del
platillo tibial lateral.
Condropatía superficial del resto de los compartimentos femorotibiales.
Condropatía lesiones grado 2 y 3 de la rótula.
Leve derrame articular con discreta sinovitis difusa.
Raw reply:
```json
{
  "lateral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'lateral_osteoarthritis': 1}
=== Match 15 (rule AND llm → keep; veto → mask conf=0) ===
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 16 ===
Asked keys : ['acl_tear', 'mcl_tear', 'lateral_osteoarthritis']
Report (414 chars):
Technique: MRI of the knee. ACL normal. MCL normal. Medial meniscus tear. Lateral meniscus tear. Incipient OA of all three compartmens.  Baker's cyst present. Large effusion. Insufficient fracture of medial femoral condyl with adjacent bone marrow oedema. Conclusion: Medial meniscus tear. Lateral meniscus tear. Incipient OA of all three compartmens.  Baker's cyst present. Large effusion. Medial condyl fracture.
Raw reply:
```json
{
  "acl_tear": 0,
  "mcl_tear": 1,
  "lateral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 0, 'mcl_tear': 1, 'lateral_osteoarthritis': 1}
=== Match 16 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=0 → veto (label=0, conf=0 masked)
  mcl_tear: rule=1 llm=1 → confirm (keep 1)
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 17 ===
Asked keys : ['lateral_osteoarthritis', 'patellofemoral_osteoarthritis']
Report (3101 chars):
Exam Type: MRI KNEE LEFT WO CONTRAST
Exam Date and Time: [DATE] [TIME]
Indication: Pain.
Comparison: [REDACTED].

TECHNIQUE:
MRI of the lumbar knee was performed on a 3.0 Tesla system with a dedicated knee coil in three planes (axial, sagittal, and coronal), using a standard non-contrast protocol.

FINDINGS:
OSSEOUS STRUCTURES:
Minimal degenerative subchondral bone marrow edema is present at the lateral tibiofemoral compartment related to overlying chondrosis. No acute fracture or bone bruise. Background marrow signal is normal without infiltrative marrow process. No aggressive osseous lesions.

JOINT SPACE:
Small joint effusion. No intra-articular bodies. Moderate-sized Baker cyst with slight surrounding edema likely representing leakage.

There are postoperative changes anteriorly consistent with previous arthroscopic surgery.

MEDIAL COMPARTMENT:
Medial meniscus: Normal in morphology and signal.
Medial compartment cartilage: Cartilage appears intact.

LATERAL COMPARTMENT:
Lateral meniscus: There is a diminutive appearance of the body and posterior horn consistent with previous partial meniscectomy. There is irregularity of the inner margin diffusely consistent with recurrent tear. There is moderate extrusion.
Lateral compartment cartilage: Mild cartilage thinning and fissuring is present at the posterior and peripheral weightbearing aspect, with minimal degenerative subchondral bone marrow edema.

PATELLOFEMORAL COMPARTMENT:
Patellofemoral compartment cartilage: There is mild cartilage thinning and surface irregularity at the patella and trochlea, medial greater than lateral.

CRUCIATE LIGAMENTS:
Anterior cruciate ligament (ACL): Normal with both bundles intact.
Posterior cruciate ligament (PCL): Normal.

COLLATERAL LIGAMENTS & POSTEROLATERAL CORNER:
Medial collatera
… [3101 chars total]
Raw reply:
```json
{
  "lateral_osteoarthritis": 1,
  "patellofemoral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'lateral_osteoarthritis': 1, 'patellofemoral_osteoarthritis': 1}
=== Match 17 (rule AND llm → keep; veto → mask conf=0) ===
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)
  patellofemoral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 18 ===
Asked keys : ['acl_tear', 'mcl_tear', 'synovitis']
Report (2215 chars):
MRI of Knee with
-3-Plane Loc, Sag PD FS, Sag T2 FS, Sag T1, Cor T2 FS, Screen Save, Ax T2 FS



* The contour of ACL is not in a straight line and increased signal intensity inside on F/S T2WI, in favor of tear.
* High signal in the soft tissue medial to the medial collateral ligament with increased signal intensity of proximal ligament (deep MCL/meniscofemoral ligament), in favor of grade 2 injury.
* High signal in the soft tissue surrounding the medial and lateral patellar retinaculum, in favor of grade 1 injury.
* Linear signal intensity in the body and posterior horn of medial meniscus with extension to the surface, in favor of tear.
* There is a gap in the posterior horn of lateral meniscus near the posterior root (Sr/Im: [ID]; [ID].
* Bone marrow edema in distal femur, proximal tibia and fibula, and lower pole of patella, suspect bone contusion.
    A subchondral linear hypointensity over posterior aspect of medial tibial plateau on T1WI and F/S T2WI, without associated contour deformity (Sr/Im: [ID]; [ID].
* Joint effusion and suprapatellar bursitis with suprapatellar and medial plicae; hypertrophy of the synovium, indicative of synovitis.
* Irregular contour of the posterior joint capsule with interstitial high signal intensity, suspect joint capsular injury/tear.
* Subcutaneous edema in distal thigh to proximal leg and intermuscular edema in the popliteal fossa.

Impression:
1. ACL tear.
2. Grade 2 injury of MCL (especially at the deep MCL/meniscofemoral ligament).
     Suspect grade 1 injury of medial and lateral patellar retinaculum.
3. Meniscal tear in the body and posterior horn of medial meniscus; suspect posterior root tear of lateral meniscus.
4. Bone contusion in distal femur, proximal tibia and fibula, and lower pole of patella.
     Subchondral fra
… [2215 chars total]
Raw reply:
```json
{
  "acl_tear": 1,
  "mcl_tear": 0,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1, 'mcl_tear': 0, 'synovitis': 1}
=== Match 18 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)
  mcl_tear: rule=1 llm=0 → veto (label=0, conf=0 masked)
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 19 ===
Asked keys : ['medial_osteoarthritis', 'lateral_osteoarthritis']
Report (1439 chars):
Antecedentes Clínicos:
Artrosis.
Hallazgos:
Ligamentos cruzados y colaterales dentro de límites normales.
El menisco medial es de morfología y señal conservada, sin criterios categóricos de rotura.
Rotura compleja degenerativa del cuerno anterior, cuerpo, cuerno posterior y parte de la raíz
meniscal posterior del menisco lateral con extrusión asociada. Edema óseo periférico posterior de
platillo tibial lateral con pequeñas fracturas subcorticales regionales.
Úlceras condrales de espesor parcial y total de la región posterior de carga del compartimento
femorotibial lateral. Mínimos cambios óseos asociados. Condropatía superficial del compartimento
femorotibial medial y del cartílago troclear.
Úlceras condrales de espesor parcial y prácticamente total de la faceta lateral de la rótula.
Leve a moderado derrame articular con mínima sinovitis. No hay quistes poplíteos patológicos.
Tendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial
dentro de límites normales.
Impresión:
Rotura compleja degenerativa del cuerno anterior, cuerpo , cuerno posterior y raíz meniscal
posterior del menisco lateral con extrusión asociada.
Condropatía lesiones grado 3 y 4 del compartimento femorotibial lateral.
Condropatía superficial del compartimento femorotibial medial y de la tróclea femoral. Condropatía
lesiones grado dos y tres de la rótula.
Leve a moderado derrame articular con mínima sinovitis
Raw reply:
```json
{
  "medial_osteoarthritis": 0,
  "lateral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'medial_osteoarthritis': 0, 'lateral_osteoarthritis': 1}
=== Match 19 (rule AND llm → keep; veto → mask conf=0) ===
  medial_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 20 ===
Asked keys : ['acl_tear', 'mcl_tear']
Report (1892 chars):
 In the medial compartment, there is buckethandle tear at the anterior horn, body and posterior horn of the medial meniscus. There is displaced meniscal fragment into the intercondylar notch. There is no focal chondrosis or chondral injury.
 The lateral compartment, there is suspicious small longitudinal vertical tear at the periphery posterior horn of the lateral meniscus. There is focal osteochondral injury a mid weightbaring lateral femoral condyle (about intact6* 1 cm).
 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact
 In the intercondylar notch, there is acute complete tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact There is no anterior tibial translation.
 There is grade II ligamentous sprain (partial tear) of the medial collateral ligament, at mid substance (deep and superficial fibers). The posteromedial oblique ligament is intact
 The lateral collateral ligament complexes are intact The popliteofibular ligament is intact The meniscopopliteal fascicles are intact
 The extensor mechanism is normal.
 Minimal amount of right knee effusion is 1. The surrounding musculature is normal. There is bone contusion at the posterolateral tibial plateau.  Acute osteochondral injury a mid weightbaring lateral femoral condyle (about intact6* 1 cm) of right knee.
  Buckethandle tear of the medial meniscus.
  Suspicious small longitudinal vertical tear at the periphery posterior horn of the lateral meniscus.
  Acute complete tear of the anterior cruciate ligament, at mid substance.
  Grade II ligamentous sprain (partial tear) of the medial collateral ligament, at mid substance (deep and superficial fibers).
  Mi
… [1892 chars total]
Raw reply:
```json
{
  "acl_tear": 1,
  "mcl_tear": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1, 'mcl_tear': 1}
=== Match 20 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)
  mcl_tear: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 21 ===
Asked keys : ['acl_tear', 'mcl_tear']
Report (1838 chars):
COMPARISON:None.

CLINICAL HISTORY:Left knee pain and swelling after fall. Medial joint line pain. Suspected bone contusion/meniscal tear.

PROCEDURE:Multisequence, multiplanar unenhanced MRI of the left knee according to routine protocol.

IMAGING FINDINGS:

Nondiagnostic scout localizing images reviewed.

The lateral meniscus is intact. The medial meniscus is intact.

High-grade partial-thickness tear involving the anterior cruciate ligament near the femoral attachment. No anterior tibial translation. Osteochondral impaction injury posterior lateral tibial plateau and posterior medial tibial plateau without evidence of displacement and osteophyte fragment. The posterior cruciate ligament is intact.

Low-grade partial-thickness tear involving the proximal fibers of the superficial and deep medial collateral ligament. The distal fibers are intact. The posterior oblique ligament is intact.

The fibular collateral ligament is intact. Popliteus and biceps femoris tendon attachments are intact. The iliotibial band is intact.

The patellar retinacula are intact. No femoral dysplasia. The TT-TG distance measures 12 minutes, within normal limits. The quadriceps and patellar tendons are intact.

Scattered foci of mild chondrosis throughout the patellofemoral compartment. Preserved medial and lateral femorotibial articular cartilage.

Small knee joint effusion. Regional musculature is within normal limits. No suspicious focal marrow signal alteration.

IMPRESSION:
1. High-grade partial-thickness tear of the anterior cruciate ligament.
2. Low-grade partial tear of the medial collateral ligament.
3. Osteochondral impaction injuries posterior medial tibial plateau and posterior lateral tibial plateau without evidence of displaced or unstable osteochondral fragment.
4. Mild patello
… [1838 chars total]
Raw reply:
```json
{
  "acl_tear": 1,
  "mcl_tear": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1, 'mcl_tear': 1}
=== Match 21 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)
  mcl_tear: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 22 ===
Asked keys : ['lateral_osteoarthritis', 'synovitis']
Report (1217 chars):
Antecedentes Clínicos:
Artrosis.
Hallazgos:
No hay alteraciones en significativas de la médula ósea.
Ligamentos cruzados y colaterales dentro de límites normales.
Aumento de señal central del cuerno posterior y cuerpo del menisco medial que no impresiona
contactar con la superficie articular, sin caracteres propios de rotura.
Rotura del cuerno anterior, cuerpo y parte del cuerno posterior del menisco lateral con edema las
partes blandas perimeniscal es, quistes para meniscales y moderada extrusión meniscal.
Úlceras condrales de espesor parcial y prácticamente total de la zona de carga del compartimento
femorotibial lateral. Cartílagos del compartimento femorotibial medial y de la tróclea femoral sin
alteraciones. Condropatía rotuliana superficial la faceta lateral.
Leve derrame articular con mínima sinovitis.
Tendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial
dentro de límites normales.
Impresión:
Rotura compleja del menisco lateral con extrusión asociada de quistes para meniscales.
Condropatía lesiones grado 2 y 3 de la zona de carga del compartimento femorotibial lateral.
Condropatía rotuliana superficial.
Leve derrame articular con mínima sinovitis
Raw reply:
```json
{
  "lateral_osteoarthritis": 1,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'lateral_osteoarthritis': 1, 'synovitis': 1}
=== Match 22 (rule AND llm → keep; veto → mask conf=0) ===
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 23 ===
Asked keys : ['acl_tear', 'mcl_tear']
Report (3891 chars):
FINDINGS:

Fractures:
Known mildly comminuted undisplaced avulsion fracture of the tibial tuberosity involving the distal ACL insertion, anteriorly the anterior horn root insertion of the lateral meniscus, as well as posteriorly the tibial insertion of both the posterior horn of medial and lateral menisci. The fracture involves the central portion of the medial tibial plateau articular surface anteriorly and posteriorly with articular surface collapse of 3 mm anteriorly and 5 mm posteriorly, as well as a step deformity of up to 2 mm posteriorly.
Small mildly displaced avulsion fracture of the lateral corner of lateral tibial plateau [Segond fracture].
Small mild osteochondral impaction at the anterior lateral weightbearing aspect of lateral femoral condyle.
There is associated bone marrow edema associated with these fractures.

Joint alignment:
Mild widening of the medial femorotibial joint space. Otherwise preserved articular alignment.

Degenerative changes:
None.

Bone marrow signal:
Additional small area of bone marrow edema on the medial side of medial femoral condyle without evidence of associated fracture.

Anterior cruciate ligament: The distal bony avulsion with laxity of the ACL, showing some internal high T2 signal changes compatible with additional low-grade partial ligamentous tear.
Posterior cruciate ligament: Intact with mild laxity.
Medial collateral ligament: Complete tear of the superficial portion at the mid to distal third. Moderate grade partial tear of the deep meniscal femoral and meniscal tibial components with partial meniscocapsular separation of the medial meniscal body.
Lateral collateral ligament complex: Low-grade sprain of the proximal lateral collateral ligament. The other associated structures are intact.

Medial meniscus: Mild nonspecif
… [3891 chars total]
Raw reply:
```json
{
  "acl_tear": 1,
  "mcl_tear": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1, 'mcl_tear': 1}
=== Match 23 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)
  mcl_tear: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 24 ===
Asked keys : ['medial_osteoarthritis', 'lateral_osteoarthritis', 'patellofemoral_osteoarthritis', 'synovitis']
Report (1959 chars):
 In the medial compartment, there is radial tear at the posterior root of the medial meniscus. There is displaced meniscal fragment into the medial gutter. There is diffuse high grade and low grade chondrosis (less than and more than 50% thickness cartilage loss) along weightbaring medial femoral condyle and medial tibial plateau. There is subchondral edema. Osteophytes are present.

 The lateral compartment, there is small horizontal tear at the anterior horn of the lateral meniscus. There is focal high grade chondrla defectat mid lateral tibial plateau (about 1.2* 1.1 cm). There is no subchondral edema. Osteophytes are present.

 The patellofemoral joint, there is diffuse low grade and high grade chondrosis (less than and more than 50% thickness cartilage loss) along medial and lateral trochleas, medial and lateral patellar facets. There is subchondral edema. Osteophytes are present. The medial patellofemoral ligament is intact.

 In the intercondylar notch, the anterior cruciate ligament is intact. The posterior cruciate ligament is intact. There is no tibial translation.

 The medial collateral ligament complexes are intact. The posteromedial oblique ligament is intact.

 The lateral collateral ligament complexes are intact. The popliteofibular ligament is intact. The meniscopopliteal fascicles are intact.

 The extensor mechanism is normal.
 Some amount of left knee effusion with synovitis is present. A 1.5*1.5* 4.5 cm baker's cyst at the posteromedial aspect of left knee. The surrounding musculature is normal.  Tricompartmental osteoarthritis of the left knee by evidence of chondrosis, subchondral edema, and osteophytes.
  Radial tear at the posterior root of the medial meniscus. (note: meniscal extrusion into the medial gutter).
  Suspec
… [1959 chars total]
Raw reply:
```json
{
  "medial_osteoarthritis": 0,
  "lateral_osteoarthritis": 0,
  "patellofemoral_osteoarthritis": 0,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'medial_osteoarthritis': 0, 'lateral_osteoarthritis': 0, 'patellofemoral_osteoarthritis': 0, 'synovitis': 1}
=== Match 24 (rule AND llm → keep; veto → mask conf=0) ===
  medial_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  lateral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  patellofemoral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 25 ===
Asked keys : ['mcl_tear', 'medial_osteoarthritis', 'lateral_osteoarthritis', 'patellofemoral_osteoarthritis']
Report (2151 chars):
Exam Type: MRI KNEE LEFT WO CONTRAST
Exam Date and Time: [DATE] [TIME]
Indication: Left knee pain for 4 weeks after injury at gym.
Comparison: No relevant prior studies available for comparison.

TECHNIQUE:
MRI of the left knee was performed on a 1.5 Tesla system with a dedicated knee coil in three planes (axial, sagittal, and coronal), using a standard non-contrast protocol.

FINDINGS:
OSSEOUS STRUCTURES:
Alignment is anatomic. No acute fracture. Normal background marrow signal. No focal osseous lesion. Focal bone marrow edema at the anteromedial tibial plateau. Small focal osteochondral impaction injury at the posterior lateral femoral condyle.

JOINT SPACE:
No joint effusion. No Baker's cyst.

MEDIAL COMPARTMENT:
Medial meniscus: No tear.
Medial compartment cartilage: Intact.

LATERAL COMPARTMENT:
Lateral meniscus: No tear.
Lateral compartment cartilage: Intact.

PATELLOFEMORAL COMPARTMENT:
Patellofemoral compartment cartilage: Low-grade articular cartilage loss at the lateral and medial patellar facets.

CRUCIATE LIGAMENTS:
Anterior cruciate ligament (ACL): No tear.
Posterior cruciate ligament (PCL): No tear.

COLLATERAL LIGAMENTS & POSTEROLATERAL CORNER:
Medial collateral ligament (MCL): Grade 2 injury.
Lateral collateral ligament (LCL) complex: Normal.
Posterolateral corner structures: Normal.

EXTENSOR MECHANISM:
Extensor Apparatus: Normal quadriceps tendon. Normal patellar tendon.
Medial patellofemoral ligament (MPFL) and patellar retinacula: Normal.
Patellofemoral tracking: No edema in superolateral Hoffa's fat pad. No lateral patellar tilt or translation. No patella alta. Tibial tubercle-trochlear groove (TT-TG) distance is 12 mm, normal.

MUSCLES/TENDONS:
No disproportionate muscle atrophy. Visualized tendons not previously discussed are intact.

SOFT TISSUES
… [2151 chars total]
Raw reply:
```json
{
  "mcl_tear": 1,
  "medial_osteoarthritis": 0,
  "lateral_osteoarthritis": 0,
  "patellofemoral_osteoarthritis": 0
}
```
Parsed JSON for asked keys: {'mcl_tear': 1, 'medial_osteoarthritis': 0, 'lateral_osteoarthritis': 0, 'patellofemoral_osteoarthritis': 0}
=== Match 25 (rule AND llm → keep; veto → mask conf=0) ===
  mcl_tear: rule=1 llm=1 → confirm (keep 1)
  medial_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  lateral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  patellofemoral_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 26 ===
Asked keys : ['acl_tear', 'synovitis']
Report (1858 chars):
MRI of Knee with
-3-Plane Loc, Sag PD FS, Sag T2 FS, Sag T1, Cor T2 FS, Ax T2 FS



> The contour of ACL is not in a straight line and increase signal intensity inside on F/S T2WI, in favor of tear, major at proximal portion.
> The contour of PCL appears to be within normal, no abnormal signal intensity is noted.
> Joint effusion and suprapatellar bursitis with suprapatellar, lateral and medial plicae; hypertrophy of the synovium, indicative of synovitis.
> Linear signal intensity in posterior horn of medial meniscus, and increased signal of meniscocapsular junction, R/O Ramp lesion or peripheral longitudinal tear of posterior horn of medial meniscus.
> Both medial & lateral collateral ligaments appear to be within normal.
> Abnormal signal intensity is noted in proximal tibia and distal femur, which shows low signal intensity on T1WI and high signal intensity on T2WI, in favor of bone contusion, more prominent at lateral side.
  In favor of subchondral fracture of lateral femoral condyle.
> Subcutansoue edema over right knee, more prominent at anterior portion; mild deep infrapatellar bursitis.
> Focal wearing of articular cartilage of femoral trochelam reflecting grade 3-4 chondromalacia and mild subchondral edema (Srs/Img: [ID]
> Small lymph node in popliteal fossa.

Impression:
1. C/W ACL tear.
2. R/O Ramp lesion or peripheral longitudinal tear of posterior horn of medial meniscus.
3. Bone contusion in right distal femur and proximal tibia, R/O subchondral fracture of lateral femoral condyle.
4. Grade 1 injury of LCL and popliteus tendon
5. Grade 3-4 chondromalacia and mild subchondral edema of femoral trochlea(Srs/Img: [ID].
6. Moderate joint effsuion and synovitis of right knee and patellar plicae.
7. Subcutaneous edema over right knee and deep infrapatellar bur
… [1858 chars total]
Raw reply:
```json
{
  "acl_tear": 1,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1, 'synovitis': 1}
=== Match 26 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 27 ===
Asked keys : ['acl_tear', 'medial_osteoarthritis', 'lateral_osteoarthritis', 'patellofemoral_osteoarthritis']
Report (2189 chars):
 In the medial compartment, there is complex tear (main radial component) at the body and posterior horn of the medial meniscus. There is displaced meniscal fragment into the medial gutter. There is diffuse high grade and low grade chondrosis (less than and more than 50% thickness cartilage loss) along weightbaring medial femoral condyle and medial tibial plateau. There is no subchondral edema. Osteophytes are present.

 The lateral compartment, there is complex tear with buckethandle tear at the anterior horn, body and posterior horn of the lateral meniscus. There is focal high grade chondrosis at the the posterolateral tibial plateau (about 1.5* 1.9 cm). There is subchondral edema. Osteophytes are present.

 The patellofemoral joint, there is focal grade  chondrosis (less than 50% thickness cartilage loss) at the medial patellar facet (about 1.3* 1 cm). The medial patellofemoral ligament is intact.

 In the intercondylar notch, there is chronic complete tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact. There is no tibial translation.

 The medial collateral ligament complexes are intact. The posteromedial oblique ligament is intact.

 The lateral collateral ligament complexes are intact. The popliteofibular ligament is intact. The meniscopopliteal fascicles are intact.

 The extensor mechanism is normal.

 Minimal amount of right knee effusion is present.The surrounding musculature is normal.  Mild medial tibiofemoral compartmental osteoarthritis of the right knee by evidence of chondrosis, subchondral edema and osteophytes.
  Focal high grade chondrosis at the the posterolateral tibial plateau (about 1.5* 1.9 cm).
  Focal low grade  chondrosis at the medial patellar facet (about 1.3* 1 cm
… [2189 chars total]
Raw reply:
```json
{
  "acl_tear": 1,
  "medial_osteoarthritis": 1,
  "lateral_osteoarthritis": 1,
  "patellofemoral_osteoarthritis": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 1, 'medial_osteoarthritis': 1, 'lateral_osteoarthritis': 1, 'patellofemoral_osteoarthritis': 1}
=== Match 27 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=1 → confirm (keep 1)
  medial_osteoarthritis: rule=1 llm=1 → confirm (keep 1)
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)
  patellofemoral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 28 ===
Asked keys : ['medial_osteoarthritis', 'lateral_osteoarthritis', 'synovitis']
Report (392 chars):
Técnica: RMN de la rodilla. Resultados: Cambios de señal en el menisco interno sin signos de desgarro. Secuelas de osteocondritis de la tuberosidad tibial. OA femorotibial medial y lateral. OA patelofemoral. Derrame con sinovitis. Quiste subcondral en la meseta tibial lateral. Impresión: Cambios de señal en el menisco interno sin signos de desgarro. OA patelofemoral. Derrame con sinovitis.
Raw reply:
```json
{
  "medial_osteoarthritis": 0,
  "lateral_osteoarthritis": 1,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'medial_osteoarthritis': 0, 'lateral_osteoarthritis': 1, 'synovitis': 1}
=== Match 28 (rule AND llm → keep; veto → mask conf=0) ===
  medial_osteoarthritis: rule=1 llm=0 → veto (label=0, conf=0 masked)
  lateral_osteoarthritis: rule=1 llm=1 → confirm (keep 1)
  synovitis: rule=1 llm=1 → confirm (keep 1)

Both `max_new_tokens` (=160) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== LLM call 29 ===
Asked keys : ['acl_tear', 'synovitis']
Report (863 chars):
Stigmata der Inaktivitätsosteopenie sowie verbliebenes bone bruise im posterolateralen Tibiaplateau nahe der Eminentia bei subchondraler Impression mit teils punktuell chondralen Läsionen. Anamnestisch bek. VKB Ruptur mit wohl ligamentärer Ruptur des anteromedialen Bündels sowie knöchernem Ausriss des posterolateralen Bündels (4/23). Weiteres Ossikel/Flake angrenzend an die nicht sicher abgrenzbare Außenmeniskushinterhornwurzel, hier DD ebenfalls Mitbeteiligung/knöcherner Ausriss. Innenmeniskus mit horizontalem Riss Pars intermedia bis ins Hinterhorn ziehend bei mukoider Vorschädigung. Zusätzlich noch Knochenödem im medialen femorotibialen Gelenkkompartiment randständig, tibial führend, bei vorrangig Chondropathie. Begleitend geringer Gelenkerguss, Reizsynovialitis sowie gering Flüssigkeit gefüllte Baker-Zyste mit CC 3,2 cm. Kl. Plica mediopatellaris.
Raw reply:
```json
{
  "acl_tear": 0,
  "synovitis": 1
}
```
Parsed JSON for asked keys: {'acl_tear': 0, 'synovitis': 1}
=== Match 29 (rule AND llm → keep; veto → mask conf=0) ===
  acl_tear: rule=1 llm=0 → veto (label=0, conf=0 masked)
  synovitis: rule=1 llm=1 → confirm (keep 1)
Hybrid macro F1: 0.421  (rules 0.394)

,label,precision_rule,recall_rule,f1_rule,precision_hybrid,recall_hybrid,f1_hybrid,precision_delta
9,bakers_cyst,1.000000,0.250000,0.400000,1.000000,0.250000,0.400000,0.000000
11,fracture,1.000000,0.388889,0.560000,1.000000,0.388889,0.560000,0.000000
4,medial_osteoarthritis,1.000000,0.066667,0.125000,1.000000,0.133333,0.235294,0.000000
7,joint_effusion,0.761905,0.457143,0.571429,0.789474,0.428571,0.555556,0.027569
0,acl_tear,0.518519,0.583333,0.549020,0.727273,0.333333,0.457143,0.208754
8,synovitis,0.666667,0.222222,0.333333,0.636364,0.259259,0.368421,-0.030303
3,lateral_meniscus_injury,0.619048,0.565217,0.590909,0.631579,0.521739,0.571429,0.012531
2,medial_meniscus_injury,0.555556,0.384615,0.454545,0.562500,0.346154,0.428571,0.006944
10,bone_contusion,0.529412,0.473684,0.500000,0.529412,0.473684,0.500000,0.000000
1,mcl_tear,0.333333,0.777778,0.466667,0.500000,0.333333,0.400000,0.166667
6,patellofemoral_osteoarthritis,0.250000,0.142857,0.181818,0.500000,0.095238,0.160000,0.250000
5,lateral_osteoarthritis,0.000000,0.000000,0.000000,0.500000,0.363636,0.421053,0.500000

,label,precision,recall,f1,auc,support_pos,support_neg
3,lateral_meniscus_injury,0.631579,0.521739,0.571429,0.660870,23,35
11,fracture,1.000000,0.388889,0.560000,0.694444,18,40
7,joint_effusion,0.789474,0.428571,0.555556,0.627329,35,23
10,bone_contusion,0.529412,0.473684,0.500000,0.634278,19,39
0,acl_tear,0.727273,0.333333,0.457143,0.622549,24,34
2,medial_meniscus_injury,0.562500,0.346154,0.428571,0.563702,26,32
5,lateral_osteoarthritis,0.500000,0.363636,0.421053,0.639265,11,47
1,mcl_tear,0.500000,0.333333,0.400000,0.636054,9,49
9,bakers_cyst,1.000000,0.250000,0.400000,0.625000,12,46
8,synovitis,0.636364,0.259259,0.368421,0.565114,27,31
4,medial_osteoarthritis,1.000000,0.133333,0.235294,0.566667,15,43
6,patellofemoral_osteoarthritis,0.500000,0.095238,0.160000,0.520592,21,37

## 3. Generate hybrid pseudo-labels

Reuses the confirmer from 2b. The 58 labeled studies still get ground truth.

`/kaggle/working` is wiped when Jupyter restarts. This cell **loads** an existing CSV if present (`/kaggle/working/outputs/` or Dataset `simonhochwebde/rsna-knee-pseudo-labels`, including `/kaggle/input/datasets/...`). Set `FORCE_RELABEL = True` only when you want a new labeling pass.

In [15]:
from rsna_knee.reports.hybrid import load_pseudo_labels

FORCE_RELABEL = False  # True = run the LLM over all 4,407 studies again
_PSEUDO_NAMES = ("pseudo_labels.csv", "pseudo_labels.parquet")
_PSEUDO_MOUNT = Path("/kaggle/input/datasets/simonhochwebde/rsna-knee-pseudo-labels")


def _resolve_pseudo(preferred: Path) -> Path | None:
    """Find CSV/parquet; do not import persist (often missing on a stale code Dataset)."""
    bases = [
        preferred,
        Path("/kaggle/working/outputs") / "pseudo_labels.csv",
        _PSEUDO_MOUNT,
        Path("/kaggle/input/rsna-knee-pseudo-labels"),
    ]
    hits: list[Path] = []
    for base in bases:
        if base.is_file():
            hits.append(base)
            continue
        if not base.is_dir():
            continue
        for name in _PSEUDO_NAMES:
            p = base / name
            if p.is_file():
                hits.append(p)
        try:
            hits.extend(p for p in base.rglob("pseudo_labels.csv") if p.is_file())
            hits.extend(p for p in base.rglob("pseudo_labels.parquet") if p.is_file())
        except OSError:
            continue
    seen: set[str] = set()
    for path in hits:
        key = str(path)
        if key in seen:
            continue
        seen.add(key)
        if path.is_file() and path.suffix.lower() in {".csv", ".parquet"}:
            return path
    print("pseudo-label mount:", _PSEUDO_MOUNT, "exists=", _PSEUDO_MOUNT.is_dir())
    if _PSEUDO_MOUNT.is_dir():
        print("contents:", sorted(p.name for p in _PSEUDO_MOUNT.rglob("*"))[:40])
    return None


pseudo_path = Path(cfg["data"]["pseudo_labels_path"])
if not pseudo_path.is_absolute():
    pseudo_path = REPO_ROOT / pseudo_path
pseudo_path.parent.mkdir(parents=True, exist_ok=True)

found = None if FORCE_RELABEL else _resolve_pseudo(pseudo_path)
if found is not None:
    if found.resolve() != pseudo_path.resolve():
        shutil.copy2(found, pseudo_path)
    pseudo_df = load_pseudo_labels(pseudo_path)
    print(f"Loaded {pseudo_path}  shape={pseudo_df.shape}  (from {found})")
elif FORCE_RELABEL:
    llm.verbose = False
    pseudo_df = generate_pseudo_labels(
        DATA_ROOT,
        output_path=pseudo_path,
        llm_labeler=llm,
        confirm_labels=confirm_labels,
        fill_ambiguous=bool(rpt.get("fill_ambiguous", False)),
        route_threshold=float(rpt.get("route_threshold", 0.7)),
    )
    print(f"Wrote {pseudo_path}  shape={pseudo_df.shape}")
else:
    raise FileNotFoundError(
        f"No pseudo_labels.csv under {_PSEUDO_MOUNT}. "
        "If the file has another name, re-run and check the contents listing above."
    )

print(pseudo_df["label_source"].value_counts())
display(pseudo_df.head())

Loaded /kaggle/working/outputs/pseudo_labels.csv  shape=(4407, 26)  (from /kaggle/input/datasets/simonhochwebde/rsna-knee-pseudo-labels/pseudo_labels.csv)
label_source
rules           3035
hybrid          1314
ground_truth      58
Name: count, dtype: int64

,StudyInstanceUID,label_source,acl_tear,acl_tear_conf,mcl_tear,mcl_tear_conf,medial_meniscus_injury,medial_meniscus_injury_conf,lateral_meniscus_injury,lateral_meniscus_injury_conf,...,joint_effusion,joint_effusion_conf,synovitis,synovitis_conf,bakers_cyst,bakers_cyst_conf,bone_contusion,bone_contusion_conf,fracture,fracture_conf
0,1.2.826.0.1.3680043.8.498.10004873229099053869...,hybrid,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,...,1.0,0.90,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00
1,1.2.826.0.1.3680043.8.498.10004945927472656027...,rules,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00
2,1.2.826.0.1.3680043.8.498.10009278692606631573...,hybrid,0.0,0.0,0.0,0.0,0.0,0.85,0.0,0.85,...,0.0,0.85,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00
3,1.2.826.0.1.3680043.8.498.10009639203170750274...,rules,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.85,...,0.0,0.85,0.0,0.0,0.0,0.0,0.0,0.85,0.0,0.85
4,1.2.826.0.1.3680043.8.498.10013663742400736029...,rules,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00

## 3b. Keep the CSV on your PC

Kernel Dataset upload is skipped. The file stays at `/kaggle/working/outputs/pseudo_labels.csv` until this Jupyter session ends.

On your PC (session still running):

```bash
python scripts/pull_pseudo_labels.py
```

That writes `outputs/pseudo_labels.csv` (gitignored). Upload later:

```bash
python scripts/publish_pseudo_labels.py
```

In [11]:
preferred = pseudo_path if "pseudo_path" in dir() else Path("/kaggle/working/outputs/pseudo_labels.csv")
found = _resolve_pseudo(preferred) if "_resolve_pseudo" in dir() else (preferred if preferred.is_file() else None)
print("On Kaggle:", found)
if found is not None:
    print(f"size={found.stat().st_size / 1e6:.2f} MB  rows={sum(1 for _ in found.open()) - 1}")
print("Pull to PC while this session is up:  python scripts/pull_pseudo_labels.py")
print("Upload Dataset later:                 python scripts/publish_pseudo_labels.py")

On Kaggle: None
Pull to PC while this session is up:  python scripts/pull_pseudo_labels.py
Upload Dataset later:                 python scripts/publish_pseudo_labels.py

## 4. Resolve pretrained weights

In [13]:
weight_name = cfg["model"].get("pretrained_weights", "convnext_tiny_imagenet.pth")
variant = cfg["model"].get("pretrained_variant")
pretrained_path = resolve_pretrained_weights(
    filename=weight_name,
    variant=variant,
    allow_missing=bool(cfg["model"].get("allow_random_init", False)),
)
print(f"Pretrained weights: {pretrained_path}")

Pretrained weights: /kaggle/input/datasets/simonhochwebde/rsna-knee-pretrained/convnext_tiny_imagenet.pth

## 5a. Pack volume cache (local only)

Decodes DICOMs into `/kaggle/working/volume_cache` (~14 GiB). **Does not upload.**

If `d16_h256_w256_s3` already has 4407 `.npy` files, skip this cell and run the four **Upload part** cells below.

Internet ON for uploads only (parts 1-4).

In [ ]:
import gc

from rsna_knee.data import (
    materialize_writable_volume_cache,
    prepare_disk_volume_cache,
)

if "llm" in dir():
    unload = getattr(llm, "unload", None)
    if callable(unload):
        unload()
    else:
        del llm
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    print("Released LLM weights")

CACHE_DIR = Path("/kaggle/working/volume_cache") if ON_KAGGLE else REPO_ROOT / "volume_cache"
volume_shape = tuple(cfg["data"]["volume_shape"])
max_series = int(cfg["data"]["max_series"])
_pseudo = pseudo_path if "pseudo_path" in dir() else cfg["data"].get("pseudo_labels_path")

cache_ds = prepare_disk_volume_cache(
    DATA_ROOT,
    CACHE_DIR,
    labeled_only=bool(cfg["data"].get("labeled_only", False)),
    pseudo_labels_path=_pseudo,
    min_confidence=float(cfg["data"].get("min_confidence", 0.7)),
    volume_shape=volume_shape,
    max_series=max_series,
    max_workers=8,
)
n_copied = materialize_writable_volume_cache(cache_ds)
n_npy = len(list(cache_ds.cache_dir.glob("*.npy")))
print(f"Cache ready: {cache_ds.cache_dir}  npy={n_npy}  copied_from_mounts={n_copied}")
print("Next: run Upload part 1, then 2, then 3 (internet ON).")

## 5a. Upload part 1 / 4 (~3 GiB)

Internet **ON**. Run this cell alone; wait until it finishes before part 2.

Creates Dataset `simonhochwebde/rsna-knee-volume-cache-p1`.

In [21]:
from pathlib import Path

from rsna_knee.data.volume_cache import push_volume_cache_part

CACHE_DIR = Path("/kaggle/working/volume_cache/d16_h256_w256_s3")
print("cache:", CACHE_DIR)
push_volume_cache_part(CACHE_DIR, 1, n_parts=4)
print("Part 1/4 done. Run Upload part 2.")

ImportError: cannot import name 'push_volume_cache_part' from 'rsna_knee.data.volume_cache' (/kaggle/working/src/rsna_knee/data/volume_cache.py)

## 5a. Upload part 2 / 4

In [ ]:
from pathlib import Path

from rsna_knee.data.volume_cache import push_volume_cache_part

CACHE_DIR = Path("/kaggle/working/volume_cache/d16_h256_w256_s3")
print("cache:", CACHE_DIR)
push_volume_cache_part(CACHE_DIR, 2, n_parts=4)
print("Part 2/4 done. Run Upload part 3.")

## 5a. Upload part 3 / 4

In [ ]:
from pathlib import Path

from rsna_knee.data.volume_cache import push_volume_cache_part

CACHE_DIR = Path("/kaggle/working/volume_cache/d16_h256_w256_s3")
print("cache:", CACHE_DIR)
push_volume_cache_part(CACHE_DIR, 3, n_parts=4)
print("Part 3/4 done. Run Upload part 4.")

## 5a. Upload part 4 / 4

After success: attach `rsna-knee-volume-cache-p1`, `-p2`, `-p3`, `-p4` on the kernel, restart Jupyter, then run **5b Train**.

In [ ]:
from pathlib import Path

from rsna_knee.data.volume_cache import push_volume_cache_part

CACHE_DIR = Path("/kaggle/working/volume_cache/d16_h256_w256_s3")
print("cache:", CACHE_DIR)
push_volume_cache_part(CACHE_DIR, 4, n_parts=4)
print("Part 4/4 done. Attach all four Datasets and restart Jupyter.")

## 5b. Train on pseudo-labels (OOF on 58 labeled)

Reads packed volumes from `/kaggle/working/volume_cache` and/or Datasets `rsna-knee-volume-cache-p1` … `-p4`. Does not re-decode DICOMs. Prefer GPU (T4), internet OFF.

In [ ]:
import inspect

from rsna_knee.training import loop as _train_loop

CKPT_DIR = Path(cfg["paths"]["checkpoint_dir"])
if not CKPT_DIR.is_absolute():
    CKPT_DIR = REPO_ROOT / CKPT_DIR
CKPT_DIR.mkdir(parents=True, exist_ok=True)

volume_shape = tuple(cfg["data"]["volume_shape"])
max_series = int(cfg["data"]["max_series"])
MAX_EPOCHS = int(cfg["training"]["max_epochs"])
if DEVICE.type == "cpu":
    MAX_EPOCHS = min(MAX_EPOCHS, 1)

if "CACHE_DIR" not in dir():
    CACHE_DIR = Path(cfg["data"]["cache_dir"] or "/kaggle/working/volume_cache")

print("loop.py:", _train_loop.__file__)
print("cache_dir:", CACHE_DIR)
_kfold_params = inspect.signature(_train_loop.run_kfold_training).parameters
train_kw = dict(
    n_folds=int(cfg["training"]["n_folds"]),
    max_epochs=MAX_EPOCHS,
    batch_size=int(cfg["training"]["batch_size"]),
    learning_rate=float(cfg["training"]["learning_rate"]),
    volume_shape=volume_shape,
    max_series=max_series,
    checkpoint_dir=CKPT_DIR,
    seed=int(cfg["seed"]),
    pretrained_path=pretrained_path,
    allow_random_init=bool(cfg["model"].get("allow_random_init", False)),
    tta=bool(cfg["inference"].get("tta", False)),
    num_workers=int(cfg["data"].get("num_workers", 0)),
    model_name=cfg["model"]["name"],
    use_amp=bool(cfg["training"].get("amp", True)),
    gpu_cache=bool(cfg["training"].get("gpu_cache", False)),
    data_parallel=bool(cfg["training"].get("data_parallel", False)),
    parallel_folds=cfg["training"].get("parallel_folds"),
    slice_chunk=int(cfg["model"].get("slice_chunk", 16)),
    labeled_only=bool(cfg["data"].get("labeled_only", False)),
    pseudo_labels_path=pseudo_path if "pseudo_path" in dir() else cfg["data"].get("pseudo_labels_path"),
    min_confidence=float(cfg["data"].get("min_confidence", 0.7)),
    confidence_weighted_loss=bool(cfg["training"].get("confidence_weighted_loss", True)),
    eval_labeled_only=bool(cfg["training"].get("eval_labeled_only", True)),
    mixup_alpha=float(cfg["training"].get("mixup_alpha", 0.4)),
    use_multimodal=bool(cfg["model"].get("use_multimodal", False)),
    text_model_path=cfg["model"].get("text_model_path"),
    cache_dir=str(CACHE_DIR),
    warm_cache=False,
)
dropped = [k for k in train_kw if k not in _kfold_params]
train_kw = {k: v for k, v in train_kw.items() if k in _kfold_params}
if dropped:
    print("Dropped kwargs not in this loop.py:", dropped)

train_result = run_phase2_training(DATA_ROOT, **train_kw)

print(f"OOF macro ROC-AUC (58 labeled): {train_result['overall_auc']:.4f}")
print("Phase 1 baseline (from-scratch, 58 only): 0.5295")

## 6. Per-label OOF detail

In [ ]:
train = load_train_table(DATA_ROOT)
labeled_mask = labels_present_mask(train)
labeled_ids = set(train.loc[labeled_mask, "StudyInstanceUID"].astype(str))
labeled_idx = [i for i, uid in enumerate(train_result["study_ids"]) if uid in labeled_ids]

oof_preds = train_result["oof_preds"][labeled_idx]
oof_labels = train_result["oof_labels"][labeled_idx]
print("OOF macro ROC-AUC:", macro_roc_auc(oof_labels, oof_preds))

from sklearn.metrics import roc_auc_score
rows = []
for i, name in enumerate(TARGET_LABELS):
    yt = oof_labels[:, i]
    if len(np.unique(yt)) < 2:
        rows.append({"label": name, "auc": float("nan")})
        continue
    rows.append({"label": name, "auc": float(roc_auc_score(yt, oof_preds[:, i]))})
display(pd.DataFrame(rows).sort_values("auc", ascending=False))

## 7. Test inference → submission.csv (image-only)

In [ ]:
ckpt_paths = [fr.checkpoint_path for fr in train_result["fold_results"]]
study_ids, test_preds = predict_test_ensemble(
    ckpt_paths,
    DATA_ROOT,
    volume_shape=volume_shape,
    max_series=max_series,
    batch_size=int(cfg["training"]["batch_size"]),
    tta=bool(cfg["inference"].get("tta", False)),
    allow_random_init=True,
    model_name=cfg["model"]["name"],
    num_workers=int(cfg["data"].get("num_workers", 0)),
    use_amp=bool(cfg["training"].get("amp", True)),
    slice_chunk=int(cfg["model"].get("slice_chunk", 16)),
)

sub = predictions_to_submission(study_ids, pd.DataFrame(test_preds, columns=TARGET_LABELS))
sub_path = OUT_DIR / "submission.csv"
sub.to_csv(sub_path, index=False)
print(f"Wrote {sub_path}  shape={sub.shape}")
display(sub.head())

## 8. Optional — multimodal experiment

Set `model.use_multimodal: true` and attach a clinical text encoder Dataset. Re-run section 5 with fusion at train time; inference remains image-only.